version: "3.8"
services:
    minio-latest:
        image: minio/minio:latest
        restart: always
        container_name: minio-latest
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ./minio/data:/data
            - ./minio/config:/root/.minio
        environment:
            - MINIO_ROOT_USER=admin
            - MINIO_ROOT_PASSWORD=12345678
        command: server /data --console-address ":9001"
