version: "3.8"
services:
    minio-latest:
        # image: minio/minio:latest
        # 这是最后一个可以在web ui组建副本站点(Site Replication)的非企业版的版本，后续版本在web ui上去掉了副本站点组建功能，且后续的版本web ui功能越来越少
        # Site Replication，站点复制
        #    可通过web ui操作
        #    每个站点有完整数据副本，用于跨站点数据备份，当主站点发生故障时，可切换到从站点
        #    配置副本站点时，要求所有节点部署的minio版本必须一致，且被加入的从节点(peer site节点)不能有数据(bucket，object，IAM策略等)
        image: minio/minio:RELEASE.2024-11-07T00-52-20Z
        restart: always
        container_name: oss-minio
        ports:
            - 9000:9000
            - 9001:9001
        # 使用外部挂载存储卷存储数据和minio配置,可在容器重启后依然保留数据和secret等配置
        volumes:
            - ./minio/data:/data
            - ./minio/config:/root/.minio
        environment:
            - MINIO_ROOT_USER=admin
            - MINIO_ROOT_PASSWORD=12345678
        command: server /data --console-address ":9001"
# web可视化界面：http://localhost:9001，用户名：admin，密码：12345678
# S3 API接口地址：http://localhost:9000
# 端口说明：
# Web控制台端口默认是9001，S3 API端口默认是9000
# --console-address 可指定Web控制台端口，--address 可指定S3 API端口，如：
# command: server /data --console-address ":9001" --address ":8001"
# 一般不建议改变S3 API端口,会影响S3 API的访问，建议只改变Web控制台端口

# ================================= rancher搭建minio集群 ==================================
# test-oss-cluster-site-{1...4}

# deployment

# clusterip 9000 和容器端口相同
# clusterip  9001 和容器端口相同

# MINIO_ROOT_USER admin
# MINIO_ROOT_PASSWORD 12345678
# TZ Asia/Shanghai
# MINIO_STORAGE_CLASS_STANDARD EC:2

# 主机目录/映射为容器
# minio-site-config-path
# /data/test-oss-cluster/node1/config/minio /root/.minio

# 主机目录/映射为容器
# minio-site-data-path
# /data/test-oss-cluster/node1/data /data

# server http://test-oss-cluster-site-{1...10}:9000/data --console-address ":9001"

# 网络主机名
# test-oss-cluster-site-{1...4}

# 标签
# test-oss-cluster=adela-test-minio-site

# http://oss.test.adelacloud.sensetime.com

# 查看节点状态
# curl -I http://test-oss-cluster-site-1:9000/minio/health/live
