version: "3.8"
services:
    minio-latest:
        image: minio/minio:latest
        restart: always
        container_name: minio-latest
        ports:
            - 9000:9000
            - 9001:9001
        # 使用外部挂载存储卷存储数据和minio配置,可在容器重启后依然保留数据和secret等配置
        volumes:
            - ./minio/data:/data
            - ./minio/config:/root/.minio
        environment:
            - MINIO_ROOT_USER=admin
            - MINIO_ROOT_PASSWORD=12345678
        command: server /data --console-address ":9001"
# web可视化界面：http://localhost:9001，用户名：admin，密码：12345678
# S3 API接口地址：http://localhost:9000
# 端口说明：
# Web控制台端口默认是9001，S3 API端口默认是9000
# --console-address 可指定Web控制台端口，--address 可指定S3 API端口，如：
# command: server /data --console-address ":9001" --address ":8001"
# 一般不建议改变S3 API端口,会影响S3 API的访问，建议只改变Web控制台端口
