version: "3.8"
services:
    mysql:
        # mysql:8.0.25
        image: mysql:latest
        restart: always
        container_name: mysql
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/my.cnf
            # 数据库还原目录 可将需要还原的sql文件放在这里
            # - ./mysql/source:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Asia/Shanghai
        ports:
            - 3306:3306
# 连接地址：
# mysql://root:root@0.0.0.0:3306/db
# jdbc:mysql://0.0.0.0:3306/?allowPublicKeyRetrieval=true

# 注意3306端口可能被已有的mysql占用，使用 systemctl stop/status mysql 查看
