version: "3.8"
services:
    project_docker_compose_name:
        image: nginx:latest
        restart: always
        container_name: project_comtainer_name
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/cert:/etc/nginx/cert
            - ./nginx/logs:/var/log/nginx
        ports:
            - 80:80
            - 443:443
        environment:
            - TZ=Asia/Shanghai
# 注意80端口可能被Apache占用，使用 systemctl stop/status apache2 查看
