version: "3.8"
services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgres/db:/var/lib/postgresql/data
        environment:
            - PGDATA=/var/lib/postgresql/data
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        # postgres连接的url: postgres://admin:admin@localhost:5432

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        container_name: pgadmin
        ports:
            - 5433:80
        volumes:
            - ./postgres/pgadmin:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin@example.com # 必须是邮箱格式
            PGADMIN_DEFAULT_PASSWORD: pgadmin
            PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
            PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
        # pgadmin连接的url: http://localhost:5433
        # pgadmin登录用户名: pgadmin
        # pgadmin登录密码: pgadmin
        # pgadmin添加数据库连接: 仪表盘-快速连接-添加服务器
        # 注意: pgadmin启动不了可能是挂载的目录权限问题，授权: sudo chmod 777 -R postgres
