version: "3.8"
services:
    python_project_docker_compose_service_name:
        image: node:20.11.1
        restart: always
        container_name: python_project_comtainer_name
        ports:
            # python程序启动端口映射
            - 3579:3579
        volumes:
            # 以下写法，应用程序应放在本地相对于本文件的上一层目录，并将上层目录映射到docker内部的/usr/src/app中
            - ../:/usr/src/app
        environment:
            FLASK_ENV: development
        command:
            - sh
            - -c
            - |
                cd /usr/src/app
                pip install -r requirements.txt
                python -m server
